### ISSUE TITLE
Location::get() returns false

### ISSUE THREAD

**Issue by tochie-daniels** [stevebauman/location#35]
Hi,

Location::get() return 'false' when called in production server. However it returns an object when in localhost.

Any ideas why?

Regards.

**Comment by stevebauman** [comment]
Hi @tochie-daniels,

Sounds like each driver is failing to return a response.

Do you have `allow_url_fopen` in your PHP.ini on your production server?

**Comment by tochie-daniels** [comment]
Thanks @stevebauman. 
Yes, allow_url_fopen is set to ON on production server.

**Comment by stevebauman** [comment]
Hmmm, could you post your location configuration file?

**Comment by tochie-daniels** [comment]
Here is the location config file:

`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Driver
    |--------------------------------------------------------------------------
    |
    | The default driver you would like to use for location retrieval.
    |
    */

    'driver' => Stevebauman\Location\Drivers\IpInfo::class,

    /*
    |--------------------------------------------------------------------------
    | Driver Fallbacks
    |--------------------------------------------------------------------------
    |
    | The drivers you want to use to retrieve the users location
    | if the above selected driver is unavailable.
    |
    | These will be called upon in order.
    |
    */

    'fallbacks' => [

        Stevebauman\Location\Drivers\FreeGeoIp::class,

        Stevebauman\Location\Drivers\GeoPlugin::class,

        Stevebauman\Location\Drivers\MaxMind::class,

    ],

    /*
    |--------------------------------------------------------------------------
    | MaxMind Configuration
    |--------------------------------------------------------------------------
    |
    | The configuration for the MaxMind driver.
    |
    | If web service is enabled, you must fill in your user ID and license key.
    |
    | If web service is disabled, it will try and retrieve the users location
    | from the MaxMind database file located in the local path below.
    |
    */

    'maxmind' => [

        'web' => [

            'enabled' => false,

            'user_id' => '',

            'license_key' => '',

            'options' => [

                'host' => 'geoip.maxmind.com',

            ],

        ],

        'local' => [

            'path' => database_path('maxmind/GeoLite2-City.mmdb')

        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Localhost Testing
    |--------------------------------------------------------------------------
    |
    | If your running your website locally and want to test different
    | IP addresses to see location detection, set 'enabled' to true.
    |
    | The testing IP address is a Google host in the United-States.
    |
    */

    'testing' => [

        'enabled' => false,

        'ip' => '',

    ],

];
`

**Comment by apocalyarts** [comment]
having the same problem on my production server (laravel forge). Config is the same as the above one, allow_url_fopen also true.

**Comment by chmoelders** [comment]
Same here. Works on vagrant/homestead but not in production.

**Comment by stevebauman** [comment]
@chmoelders, does your recent pull request resolve this for you?

**Comment by chmoelders** [comment]
Yes, it does.

**Comment by stevebauman** [comment]
Gotcha, sorry for the late reply here. Patching tonight thanks!

**Comment by stevebauman** [comment]
Fixed in `v3.0.1`, sorry for the delay!

**Comment by murtaza-20** [comment]
@stevebauman I am still facing the issue in my production (Amazon AWS). It is working fine on my local vagrant/homestead. Can you please help?

**Comment by DevgirlTaabi** [comment]
same issue here , I am trying to get location by ip and it is returning false.

**Comment by Rolland-K** [comment]
same with my aws server.  Location::get() returns false

**Comment by keroles19** [comment]
same return false v6.5

**Comment by qaziumar** [comment]
I also got the same issue and after pulling my hair for a long I found my server is behind a load balancer and the request()->IP() method of Laravel returned the server IP and not the client IP. I have used the custom method to get the real client IP.

This custom method returns the real client's IP:

`public function getIp(){
    foreach (array('HTTP_CLIENT_IP', 'HTTP_X_FORWARDED_FOR', 'HTTP_X_FORWARDED', 'HTTP_X_CLUSTER_CLIENT_IP', 'HTTP_FORWARDED_FOR', 'HTTP_FORWARDED', 'REMOTE_ADDR') as $key){
        if (array_key_exists($key, $_SERVER) === true){
            foreach (explode(',', $_SERVER[$key]) as $ip){
                $ip = trim($ip); // just to be safe
                if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE) !== false){
                    return $ip;
                }
            }
        }
    }
    return request()->ip(); // it will return the server IP if the client IP is not found using this method.
}`

Or you can use this method:

`public function getUserIpAddr(){
   $ipaddress = '';
   if (isset($_SERVER['HTTP_CLIENT_IP']))
       $ipaddress = $_SERVER['HTTP_CLIENT_IP'];
   else if(isset($_SERVER['HTTP_X_FORWARDED_FOR']))
       $ipaddress = $_SERVER['HTTP_X_FORWARDED_FOR'];
   else if(isset($_SERVER['HTTP_X_FORWARDED']))
       $ipaddress = $_SERVER['HTTP_X_FORWARDED'];
   else if(isset($_SERVER['HTTP_FORWARDED_FOR']))
       $ipaddress = $_SERVER['HTTP_FORWARDED_FOR'];
   else if(isset($_SERVER['HTTP_FORWARDED']))
       $ipaddress = $_SERVER['HTTP_FORWARDED'];
   else if(isset($_SERVER['REMOTE_ADDR']))
       $ipaddress = $_SERVER['REMOTE_ADDR'];
   else
       $ipaddress = 'UNKNOWN';    
   return $ipaddress;
}`

Pass the client real IP when you call get method as

```
$clientIp = getUserIpAddr();
$position = Location::get($clientIp);
```
[Credits:](https://stackoverflow.com/questions/33268683/how-to-get-client-ip-address-in-laravel-5)
