### ISSUE TITLE
Class 'Stevebauman\Locations\Facade\Location' not found

### ISSUE THREAD

**Issue by inGameUA** [stevebauman/location#88]
Hi there,

Trying to use this package in one of my controllers and getting this error
`Class 'Stevebauman\Locations\Facade\Location' not found`

UsersController conatins:
```
use Stevebauman\Locations\Facade\Location;
public function GeoIP()
{
	$position = Location::get();

	return $position;
}
```

router:
`
Route::get('/geoip','UsersController@GeoIP');
`

Thanks,
Best regards.

**Comment by stevebauman** [comment]
Hi @inGameUA, this was a mistake in my documentation, the actual import should be:

```
use Stevebauman\Location\Facade\Location;
```

**Not* (notice the "s" in `Locations`):
```
use Stevebauman\Locations\Facade\Location;
```

I've updated the docs, thanks!

**Comment by inGameUA** [comment]
Hm.. Still getting this error.
I'm using Laravel 8, mb there is other way to import this package in v8?

**Comment by stevebauman** [comment]
So I’m wrong again 😓, and I’ve missed an “s” in `Facades`:

```
Stevebauman\Location\Facades\Location
```

This will work.

**Comment by inGameUA** [comment]
Well yeah, previous problem seems to be fixed but now im getting this one: 
`The location driver [] does not exist.`
:)

**Comment by inGameUA** [comment]
Well i've understood that new changes made in ``config`` folder wasn't applied so after ``php artisan config:cache`` the problem got fixed. Everything is working fine.

Thanks.
